tmp

diff --git a/run_install b/run_install
--- a/run_install
+++ b/run_install
@@ -1,10 +1,8 @@
 #!/bin/bash
 
 cd ..
-sleep 10
-./splashscreen/getdocs.sh
 
-sleep 10
+./splashscreen/getdocs.sh
 
 if [ $? -e 1 ]; then
     echo "error in DOC update procedure"
@@ -12,19 +10,27 @@ if [ $? -e 1 ]; then
     exit 1
 fi
 
-sleep 10
+
 ./splashscreen/getyocto.sh
 
 if [ $? -e 1 ]; then
     zenity --error --title="network error" --text="Unable to retrieve sources packet"
     exit 1
 fi
-sleep 10
+
 
 ./splashscreen/getsdk.sh
 
 if [ $? -e 1 ]; then
     zenity --error --title="network error" --text="Unable to retrieve sdk packet"
+    exit 1
+fi
+
+
+./splashscreen/getqtcreator.sh
+
+if [ $? -e 1 ]; then
+    zenity --error --title="network error" --text="Unable to retrieve QT packet"
     exit 1
 fi
 
